// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # Search the catalogue, optionally filtered by genre and/or author
    #
    # + genre - Filter to books of this genre
    # + author - Filter to books by this author
    # + return - returns can be any of following types
    # http:Ok (Matching books)
    # http:Unauthorized (Missing or invalid sign-in)
    resource function get books(http:RequestContext ctx, string? genre, string? author, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return <ErrorUnauthorized>{body: {code: 401, message: "no verified caller on this request"}};
        }

        int effectiveLimit = clampLimit('limit);
        int effectiveOffset = clampOffset(offset);

        Book[] matching = filterCatalogue(genre, author);
        int total = matching.length();
        Book[] page = pageOf(matching, effectiveOffset, effectiveLimit);

        string? next = effectiveOffset + effectiveLimit < total
            ? pageUri(genre, author, effectiveLimit, effectiveOffset + effectiveLimit)
            : ();
        string? previous = effectiveOffset > 0
            ? pageUri(genre, author, effectiveLimit, offsetForPrevious(effectiveOffset, effectiveLimit))
            : ();

        return <inline_response_200>{count: total, next, previous, data: page};
    }

    # Read one book's detail and current availability
    #
    # + return - returns can be any of following types
    # http:Ok (The book)
    # http:NotFound (No book with this id)
    # http:Unauthorized (Missing or invalid sign-in)
    resource function get books/[string id](http:RequestContext ctx) returns Book|ErrorNotFound|ErrorUnauthorized {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return <ErrorUnauthorized>{body: {code: 401, message: "no verified caller on this request"}};
        }

        Book? book = findBook(id);
        if book is () {
            return <ErrorNotFound>{body: {code: 404, message: "no book with this id"}};
        }
        return book;
    }
}

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Book record {
    string id;
    string title;
    string author;
    string genre;
    int year;
    boolean available;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Book[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
